spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/student.com
spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
